#!/bin/bash
# Quick check script to see if audio files on server are bilingual or Korean-only

echo "🔍 Checking Audio Files on Digital Ocean Server"
echo "================================================"
echo ""
echo "📋 Instructions:"
echo ""
echo "1. SSH to your Digital Ocean droplet:"
echo "   ssh root@your-droplet-ip"
echo ""
echo "2. Navigate to your app directory:"
echo "   cd /path/to/your/app"
echo ""
echo "3. Check audio file sizes:"
echo "   ls -lh static/audio/*.mp3 | head -10"
echo ""
echo "4. Look at the file sizes:"
echo "   • Korean-only files: ~3,000-5,000 bytes"
echo "   • Bilingual files: ~10,000-20,000 bytes"
echo ""
echo "5. If files are small (Korean-only), delete them:"
echo "   rm -f static/audio/*.mp3"
echo ""
echo "6. Restart your app:"
echo "   sudo systemctl restart wuta"
echo "   # OR if using Docker:"
echo "   docker restart wuta"
echo ""
echo "7. New audio will regenerate with Korean + English!"
echo ""
echo "================================================"
echo "🚀 OR use the automated fix script:"
echo "   ./fix_audio_on_server.sh"
